apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-helloworld
  namespace: argocd
  labels:
    name: argo-app-helloworld
    type: argocd
spec:
  project: argo-project-helloworld
  source:
    repoURL: https://github.com/pai12345/Andromeda_Infrastructure.git
    targetRevision: HEAD
    path: Kubernetes/hellow_world
    directory:
      recursive: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
